### PR TITLE
defconfigs: Set SELinux as default security mechanism

### PR DESCRIPTION
**Pull request by handymenny**
Change-Id: Ia04e276ebbc56f2c3aef25484168f1b91c80af0c
Signed-off-by: Andrea Mennillo handymenny@outlook.com

### CODE REVIEW

**Comment by handymenny** [comment]
@Agontuk This change enables SELinux.

**Comment by Agontuk** [comment]
Thanks, but I've already committed this in my local branch some days ago. I won't upload it now cause we need proper selinux policy files. You can try to see the dmesg log and make the .te files, that'll be helpful :)

**Comment by handymenny** [comment]
Ok. I'm working on the sepolicies, but before look to the dmesg we need to define a domain for every service (ps -Z | grep :init: should only list the init process). 
I have a question, we need all these services? For example: what is the usefulness of usbid_init?

**Comment by Agontuk** [comment]
It is needed to declare that system is booted. Otherwise ADB won't work.

**Comment by handymenny** [comment]
Ok, if you want you can see the development of the selinux policy here: https://github.com/HandyMenny/android_device_sony_montblanc-common

**Comment by Agontuk** [comment]
Nice work. I'll take a look after I make a new weekly build today.

**Pull request closed without merging**
