### PR TITLE
F2fs

### PR DESCRIPTION
**Pull request by handymenny**
f2fs updated to adecc452383b9394e75417c4516924ac00519ac0 of
https://kernel.googlesource.com/pub/scm/linux/kernel/git/jaegeuk/f2fs/+/linux-3.4

### CODE REVIEW

**Comment by handymenny** [comment]
The feature that this backport of f2fs hasn't is extent_cache, I wasn't able to backport it.

I'm using it, the difference in smooth is noticeable, even when compared with the previous backport. The boot is slow, or rather the phone stucks on sony logo more time ( + 2-3 seconds) and f2fs is more prone to corruption than ext4.
I'm using the following mount flags:
noatime,nosuid,nodev,nodiratime,inline_xattr,inline_data,inline_dentry,flush_merge

**Comment by handymenny** [comment]
I have updated and cleaned this pull request.
I'm closing it because you are already working on f2fs.

**Comment by Agontuk** [comment]
I'm not sure of using this yet. In your port, did you face any fails when kernel checks for error using fsck.f2fs ?

**Comment by handymenny** [comment]
This is the regular output: https://gist.github.com/HandyMenny/8a0e2869f76484352338
This is the output of fsck.f2fs in recovery: https://gist.github.com/HandyMenny/c8193a754a4fa9174a72
This is the output after doing a filesystem check in recovery: https://gist.github.com/HandyMenny/dcf16ac9be9e15cd4fc5

The strange thing is that the filesystem check never fails in recovery.

**Comment by Agontuk** [comment]
hmm, didn't check in recovery but got errors like this in normal boot. Don't know if it can be ignored.

**Pull request closed without merging**
